### ISSUE TITLE
Rendering Error Ocurred

### ISSUE THREAD

**Issue by danieldogeanu** [foundation/panini#97]
Hi guys,

I have this really weird situation, I'm trying to run Panini and I get the following error:

```
[08:10:40] Using gulpfile D:\DEVELOPMENT\REPOSITORIES\DanielDogeanu\gulpfile.js
[08:10:40] Starting 'html'...
[08:10:40] Finished 'html' after 508 ms
Panini: rendering error ocurred.
 RangeError: Maximum call stack size exceeded
    at Object.eval (eval at createFunctionContext (D:\DEVELOPMENT\REPOSITORIES\DanielDogeanu\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), <anonymous>:6:161)
    at main (D:\DEVELOPMENT\REPOSITORIES\DanielDogeanu\node_modules\handlebars\dist\cjs\handlebars\runtime.js:173:32)
    at ret (D:\DEVELOPMENT\REPOSITORIES\DanielDogeanu\node_modules\handlebars\dist\cjs\handlebars\runtime.js:176:12)
    at ret (D:\DEVELOPMENT\REPOSITORIES\DanielDogeanu\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:525:21)
    at Object.invokePartial (D:\DEVELOPMENT\REPOSITORIES\DanielDogeanu\node_modules\handlebars\dist\cjs\handlebars\runtime.js:273:12)
    at Object.invokePartialWrapper [as invokePartial] (D:\DEVELOPMENT\REPOSITORIES\DanielDogeanu\node_modules\handlebars\dist\cjs\handlebars\runtime.js:68:39)
    at Object.eval (eval at createFunctionContext (D:\DEVELOPMENT\REPOSITORIES\DanielDogeanu\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), <anonymous>:55:28)
    at main (D:\DEVELOPMENT\REPOSITORIES\DanielDogeanu\node_modules\handlebars\dist\cjs\handlebars\runtime.js:173:32)
    at ret (D:\DEVELOPMENT\REPOSITORIES\DanielDogeanu\node_modules\handlebars\dist\cjs\handlebars\runtime.js:176:12)
    at ret (D:\DEVELOPMENT\REPOSITORIES\DanielDogeanu\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:525:21)
```
The files compile just fine, except for the {{root}} not compiling into the proper file paths.

Can you help me fix this error? Thanks!

**Comment by w-biggs** [comment]
I was having this issue too, and it turned out it was because I had two partials `resource-modal` and `login-modal` that were referencing a separate `modal` partial; I think that caused Panini/Handlebars to somehow think they were referencing themselves, which caused an infinite loop. Changing the name of the partial to `modal-template` solved the issue.

I'm guessing this happens because Panini/Handlebars is looking for partials whose filenames *include* whatever you ask for, instead of partials whose filenames *equal* it, so `{{> modal}}` finds `{{> login-modal}}`, for example.

**Comment by DanielRuf** [comment]
Closiing as stale.
